---

- hosts: db

  gather_facts: yes

  become: true

  tasks:
  - name: Installing MongoDB
    apt: pkg=mongodb state=present

  # Make sure state is absent
  - name: Removing the Mongodb.conf
    file:
      path: /etc/mongodb.conf
      state: absent


  - name: Creating MongoDB file, granting read and write permissions
    file:
      path: /etc/mongodb.conf
      state: touch
      mode: u=rw,g=r,o=r

  # Blockinfile module to insert text into specified file
  - name: Setting MongoDB IP to port 27017
    blockinfile:
      path: /etc/mongodb.conf
      backup: yes
      block: |
        storage:
          dbPath: /var/lib/mongodb
          journal:
            enabled: true
        systemLog:
          destination: file
          logAppend: true
          path: /var/log/mongodb/mongod.log
        net:
          port: 27017
          bindIp: 0.0.0.0